nfc: pn547: use ioremap instead of ioremap_nocache
ioremap_nocache is not present on this kernel.

../drivers/nfc/pn547.c:1750:24: error: implicit declaration of function 'ioremap_nocache' [-Werror,-Wimplicit-function-declaration]
 1750 |                 pn547_dev->clkctrl = ioremap_nocache(pn547_dev->clkctrl_addr, 0x4);
      |                                      ^
../drivers/nfc/pn547.c:1750:24: note: did you mean 'ioremap_cache'?
../arch/arm64/include/asm/io.h:184:22: note: 'ioremap_cache' declared here
  184 | extern void __iomem *ioremap_cache(phys_addr_t phys_addr, size_t size);
      |                      ^
../drivers/nfc/pn547.c:1750:22: error: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
 1750 |                 pn547_dev->clkctrl = ioremap_nocache(pn547_dev->clkctrl_addr, 0x4);
      |                                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

Signed-off-by: Nahuel Gómez <nahuelgomez329@gmail.com>